resource_group_name = "rg-t7"
resource_group_location = "West Europe"
virtual_network_name = "vnet-t7"
subnet_name = "ehealth-subnet-t7"
vnet_address_space = "10.0.0.0/16"
subnet_address_prefix = "10.0.2.0/24"
network_security_group_name = "nsg-ehealth-t7"
network_interface_name = "nic-ehealth-t7"
